### PR TITLE
Alternate provider fix

### LINKED ISSUE #1091: AlternateProvider should not be used if not set in config
### Description

Right now in `constants.go` on oracle node v1.0.6,
```
var DefaultProvider = "http://127.0.0.1:8545"
var DefaultAlternateProvider = "http://127.0.0.1:8545"
```

If a user doesn’t set `alternateProvider` in config using `setConfig` command, than oracle node will pick up default value from constants.go as alternate provider and try to make contract calls using the same (default value is set to local host which is Invalid RPC on SKALE), so that can create problems when our primary RPC is down.

### Solution

Alternate provider should not be used if it not set in config by user rather than picking up default value from constants.go.

### PR DESCRIPTION
**Pull request by Yashk767**
# Description

Added a check whether `alternateProvder` is not set or equal to empty string before accessing feature of alternate provider.

Fixes #1091

### CODE REVIEW

File: cmd/config-utils.go [hunk 1]
```diff
@@ -129,14 +129,14 @@ func (*UtilsStruct) GetProvider() (string, error) {
 func (*UtilsStruct) GetAlternateProvider() (string, error) {
 	alternateProvider, err := flagSetUtils.GetRootStringAlternateProvider()
 	if err != nil {
-		return core.DefaultAlternateProvider, err
+		return "", err
 	}
 	if alternateProvider == "" {
 		if viper.IsSet("alternateProvider") {
-			alternateProvider = viper.GetString("alternateProvider")
+			alternateProvider = viper.GetString("alternatalternateProvider = viper.GetString(\"alternateProvidereProvider")
```
Comment (ashish10677) [inline cmd/config-utils.go:136]: This is a typo

**Review by ashish10677 — CHANGES_REQUESTED** [review]

File: cmd/config-utils.go (hunk 1 above)
Comment (Yashk767) [reply cmd/config-utils.go:136]: Ohh got refactored wrongly after testing it. Fixing it

Comment (Yashk767) [reply cmd/config-utils.go]: Done @ashish10677

**Review by ashish10677 — APPROVED** [review]
